### ISSUE TITLE
Please make the cyberware affinity bonus more resilient

### ISSUE THREAD

**Issue by i30817** [DaveOfDeath/DMSVP#1]
Some UGCs copied a script from the main campaign start map that adds cyberware claws to the player if he invested into cyberware affinity.

This check doesn't check if the player entity already had claws (of any kind) so they get replaced if you modify the UGC to allow imports. This is similar to what happens when you invest into rigging or decking and getting a datajack but i *suspect* - didn't verify - that this happens in the function that 'finishes' a new character in the dll not the map script, so it isn't a problem for importing.

Anyway i'm asking two things:

1. if this script can get a check modification that essentially says 'only add this if there is nothing in that cyberware slot in addition to Cyberware Affinity > 0'
2. check that this is not the approach used for the datajack too and if so, do the same (on your campaign only ofc).

I could modify the dll to find the datajack check inside chargen i suspect is there and add the claws to the player there, but it wouldn't do anything to the map script (notice that this isn't the first time i messed with the script engine, i already modified it to allow checks for the sony cyberdeck to also check as 'true' for 2 new datajacks i added on the dll mod - so all the dumb cyberware checks on the main campaign that check for 'if 'sony-deck' ... else if 'renkaku deck' continue working, but filtering the adding of a cyberware, i don't have enough information to check if it's 'the right' map script, so it would introduce bugs where you're *supposed* to be able to switch cyberware, like the cyberdoc screen or other campaign bonus like the claws in Callfree in Chains).

This is not the only UGC doing this, but one of the largest.

**Comment by DaveOfDeath** [comment]
This UGC is not setup to allow imported characters.  Structurally, this UGC
is based off the first game, so quite a bit of it's logic flows are round
counters / ineffecient scripts that while possible to be updated, would be
extremely time consuming.

This project is largely complete in its current state, and it's unlikely
that we'll be digging into it to change the scripting to support importing
characters.

Appreciate your interest, and you reaching out with questions... Even
though I'm unlikely to be  making the requested changes.

**Comment by i30817** [comment]
This is the only error i found with importing characters. In fact, my dll hack purposefully removes all items that are not usable in the UGC it imports to, so all inventory issues caused by that are gone too. I don't even edit the UGCs, i just hacked the dll to always allow it if not a story with a 'default' character (which often have custom stuff interacting with scripts so a 'new' character breaks the story).

it's this check: https://github.com/DaveOfDeath/DMSVP/blob/b2ce6fb8cb6a2254a347ed65374a7c132572181b/data/scenes/c01-s1_3yearsago.srt.txt#L6254

**Comment by i30817** [comment]
I made a workaround for this in my dll hack which will work for all the other UGCs doing this too (in Hong Kong : Hong Kong itself, Calfree in chains, Caldecott caper, probably something else.)

As a bonus it also prevents the other unwanted cyberware, the datajack if the character imported already has a datajack.

It does this on the method 'PlayerInventory.AttemptAddItem' which is called by scripts or the engine:

```
if (fromTrigger && (itemName == "Weapon 1 Hand Razor" && cyberwareWeapon != null || itemName == "(Head) Datajack" && HasDataJack())
            return false;
```
So if the items to add are from a script trigger, the first type of razor or datajack and the pc has equivalent already, skip it. The script trigger part means that it works on cyberdocs for all of them and the 'if there is already and it's basic' means that there is minimal disruption if you want to add them the first time, or if you try to add a custom claw (for instance) by script like calfree in chains does.
